import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  triviaContainer: {
    borderRadius: ms(28),
    padding: scale(15),
    marginBottom: vs(8),
    marginHorizontal: scale(6),
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.3)',
    flex: 1,
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: vh(15),
    minHeight: vh(90),
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(12),
  },
  questionNumber: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '600',
    opacity: 0.8,
    fontFamily: 'Century Gothic',
  },
  scoreText: {
    color: '#58CCF7',
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '600',
    fontFamily: 'Century Gothic',
  },
  questionCard: {
    backgroundColor: '#2A2A2A',
    borderRadius: ms(16),
    padding: scale(isSmallPhone ? 16 : 19),
    marginBottom: vs(16),
    flex: 1,
    position: 'relative',
    minHeight: vh(42),
  },
  questionCardWithFeedback: {
    minHeight: vh(52),
    paddingBottom: vh(12),
  },
  questionText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 15.8),
    fontWeight: '600',
    textAlign: 'left',
    marginBottom: vs(16),
    lineHeight: msFont(isSmallPhone ? 20 : isTablet ? 24 : 20.6),
    paddingHorizontal: scale(4),
    fontFamily: 'Century Gothic',
  },
  answersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: vs(24),
    paddingHorizontal: scale(7.5),
  },
  answerButton: {
    width: '48%',
    height: vs(isSmallPhone ? 60 : 65),
    borderRadius: ms(16),
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.4)',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  answerText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 15.8),
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: 'Century Gothic',
  },
  neonPill: { display: 'none' },
  neonPillText: { display: 'none' },
  selectedAnswerText: {
    color: '#FFFFFF',
  },
  correctButton: {
    borderColor: '#28A745',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  incorrectButton: {
    borderColor: '#DC3545',
    ...Platform.select({
      ios: {
        shadowColor: '#DC3545',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  feedbackContainer: {
    paddingHorizontal: scale(15),
    paddingVertical: vs(16),
    borderRadius: ms(15),
    marginHorizontal: scale(7.5),
    marginTop: vs(20),
    minHeight: vh(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  correctFeedback: {
    borderColor: '#28A745',
  },
  incorrectFeedback: {
    borderColor: '#DC3545',
  },
  feedbackGradient: { display: 'none' },
  feedbackTitle: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    marginBottom: vs(6),
    textAlign: 'center',
    fontFamily: 'Century Gothic',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  feedbackText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 14.3),
    textAlign: 'center',
    opacity: 0.95,
    lineHeight: msFont(isSmallPhone ? 18 : isTablet ? 21 : 18),
    fontFamily: 'Century Gothic',
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  continueButton: {
    backgroundColor: '#58CCF7',
    paddingVertical: vs(20),
    borderRadius: ms(16),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: vs(20),
    marginBottom: vs(24),
    marginHorizontal: scale(7.5),
    alignSelf: 'center',
    width: '96%',
    minHeight: vs(56),
    borderWidth: 2,
    borderColor: '#58CCF7',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    fontFamily: 'Century Gothic',
  },
  disabledButton: {
    backgroundColor: '#4A4A4A',
    opacity: 0.5,
  },
  disabledButtonText: {
    color: '#FFFFFF',
    opacity: 0.5,
  },
  multipleChoiceContainer: {
    marginVertical: vs(16),
    paddingHorizontal: scale(4),
    marginBottom: vs(16),
  },
  multipleChoiceContainerWithFeedback: {
    marginBottom: vh(12),
  },
  multipleChoiceButton: {
    backgroundColor: '#1C1C1C',
    paddingVertical: vs(16),
    paddingHorizontal: scale(15),
    borderRadius: ms(12),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: vs(16),
  },
  multipleChoiceText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 14.3),
    fontWeight: '500',
    textAlign: 'left',
    fontFamily: 'Century Gothic',
  },
  
  // Estilos del Modal de Felicitaciones
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  congratulationsModal: {
    width: vw(85),
    borderRadius: ms(20),
    padding: scale(22.5),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
  },
  congratulationsImage: {
    width: scale(isSmallPhone ? 130 : isTablet ? 180 : 150),
    height: scale(isSmallPhone ? 130 : isTablet ? 180 : 150),
    marginBottom: vs(24),
  },
  congratulationsTitle: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 22 : isTablet ? 28 : 24.4),
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: vs(12),
    fontFamily: 'Century Gothic',
  },
  congratulationsScore: {
    color: '#58CCF7',
    fontSize: msFont(isSmallPhone ? 28 : isTablet ? 36 : 30),
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: vs(16),
    fontFamily: 'Century Gothic',
  },
  congratulationsMessage: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 15),
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 19 : isTablet ? 23 : 20.6),
    marginBottom: vs(24),
    opacity: 0.9,
    fontFamily: 'Century Gothic',
  },
  continueFromModalButton: {
    width: '100%',
    alignSelf: 'center',
    height: vs(52),
    borderRadius: ms(16),
    overflow: 'hidden',
    backgroundColor: '#58CCF7',
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  continueFromModalGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueFromModalText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: 'bold',
    fontFamily: 'Century Gothic',
    textAlign: 'center',
  },
});
