import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: scale(15),
    paddingBottom: vh(15),
  },
  storyTitle: {
    fontSize: msFont(isSmallPhone ? 22 : isTablet ? 28 : 24.4),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(12),
    textShadowColor: 'rgba(31, 45, 85, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  slideNumber: {
    fontSize: msFont(15),
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginBottom: vs(20),
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  slideCard: {
    borderRadius: ms(25),
    padding: scale(22.5),
    marginBottom: vs(16),
    borderWidth: 3,
    borderColor: 'rgba(31, 45, 85, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  slideTitle: {
    fontSize: msFont(isSmallPhone ? 17 : isTablet ? 21 : 18.75),
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(20),
    textShadowColor: 'rgba(31, 45, 85, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 0.5,
  },
  comicFrame: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: ms(20),
    padding: scale(15),
    marginBottom: vs(24),
    borderWidth: 4,
    borderColor: '#1f2d55',
    position: 'relative',
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  comicImage: {
    width: '100%',
    height: vh(isSmallPhone ? 22 : isTablet ? 28 : 25),
    borderRadius: ms(15),
    marginBottom: vs(16),
    backgroundColor: 'rgba(31, 45, 85, 0.1)',
  },
  comicImageLarge: {
    width: '100%',
    height: vh(isSmallPhone ? 35 : isTablet ? 45 : 40),
    borderRadius: ms(20),
    backgroundColor: 'rgba(31, 45, 85, 0.05)',
  },
  speechBubble: {
    borderRadius: ms(18),
    padding: scale(15),
    borderWidth: 2,
    borderColor: '#1f2d55',
    position: 'relative',
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  bubbleTail: {
    position: 'absolute',
    bottom: -10,
    left: scale(30),
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderTopWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#1f2d55',
  },
  dialogueText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: '600',
    color: '#1a0033',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    letterSpacing: 0.5,
    fontFamily: 'Century Gothic',
  },
  slideContent: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: '600',
    color: '#1f2d55',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    marginTop: vs(16),
    letterSpacing: 0.3,
    fontFamily: 'Century Gothic',
  },
  nextSlideButton: {
    borderRadius: ms(20),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  nextSlideButtonGradient: {
    paddingVertical: vs(16),
    paddingHorizontal: scale(22.5),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: ms(18),
  },
  nextSlideButtonText: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 20 : 18),
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
    fontFamily: 'Century Gothic',
  },
  progressDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: vs(16),
    gap: scale(7.5),
  },
  dot: {
    width: scale(9.4),
    height: scale(9.4),
    borderRadius: scale(4.7),
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  activeDot: {
    backgroundColor: '#58CCF7',
    width: scale(15),
    height: scale(15),
    borderRadius: scale(7.5),
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
});
