import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gradient: {
    flex: 1,
    width: '100%',
    padding: scale(15),
    paddingTop: vs(16),
  },
  titleContainer: {
    borderRadius: ms(20),
    padding: scale(15),
    marginBottom: vs(16),
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.5)',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  title: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 21 : 18.75),
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(139, 69, 255, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginTop: vs(8),
    textShadowColor: 'rgba(88, 204, 247, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  phrasesContainer: {
    maxHeight: vh(25),
    marginBottom: vs(16),
  },
  sectionTitle: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: vs(12),
    textShadowColor: 'rgba(139, 69, 255, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  phraseItem: {
    marginBottom: vs(20),
    borderRadius: ms(18),
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.7,
        shadowRadius: 12,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  phraseGradient: {
    borderRadius: ms(18),
    minWidth: vw(70),
    maxWidth: vw(85),
    minHeight: vh(7),
    maxHeight: vh(9),
    paddingVertical: vs(8),
    paddingHorizontal: scale(15),
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phraseText: {
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 14.3),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  dragHint: {
    fontSize: msFont(isSmallPhone ? 10 : 11.25),
    fontWeight: '500',
    color: '#FFD700',
    textAlign: 'center',
    marginTop: vs(4),
    textShadowColor: 'rgba(255, 215, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  entitiesContainer: {
    marginTop: vs(16),
  },
  entitiesRow: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: vs(10),
    marginHorizontal: 0,
  },
  entityDropZone: {
    width: vw(85),
    minHeight: vh(13),
    maxHeight: vh(18),
    borderRadius: ms(18),
    paddingVertical: vs(24),
    paddingHorizontal: scale(7.5),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: vs(10),
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  entityTitle: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(8),
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  matchedItemsContainer: {
    width: '100%',
    alignItems: 'center',
  },
  matchedItem: {
    backgroundColor: 'rgba(40, 167, 69, 0.2)',
    borderRadius: ms(10),
    padding: scale(9),
    marginVertical: vs(4),
    borderWidth: 1,
    borderColor: 'rgba(40, 167, 69, 0.4)',
    width: '100%',
  },
  matchedText: {
    fontSize: msFont(isSmallPhone ? 10 : 11.25),
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: vw(85),
    borderRadius: ms(20),
    padding: scale(22.5),
    alignItems: 'flex-start',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
      },
      android: {
        elevation: 20,
      },
    }),
  },
  modalTitle: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 24 : 20.6),
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  modalText: {
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 15 : 13.5),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'left',
    alignSelf: 'stretch',
    flexWrap: 'wrap',
    lineHeight: msFont(isSmallPhone ? 18 : isTablet ? 22 : 20.6),
    marginBottom: vs(16),
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  modalButton: {
    backgroundColor: '#28A745',
    borderRadius: ms(25),
    paddingVertical: vs(12),
    paddingHorizontal: scale(30),
    borderWidth: 2,
    borderColor: 'rgba(40, 167, 69, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 10,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  completionButton: {
    backgroundColor: '#28A745',
    borderRadius: ms(25),
    paddingVertical: vs(14.5),
    paddingHorizontal: scale(37.5),
    borderWidth: 2,
    borderColor: 'rgba(40, 167, 69, 0.8)',
    ...Platform.select({
      ios: {
        shadowColor: '#28A745',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.8,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  modalButtonText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  instructionsContainer: {
    backgroundColor: 'rgba(88, 204, 247, 0.1)',
    borderRadius: ms(12),
    padding: scale(15),
    marginBottom: vs(16),
    borderWidth: 1,
    borderColor: 'rgba(88, 204, 247, 0.3)',
  },
  instructionsText: {
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 14.3),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginVertical: 2,
    opacity: 0.9,
  },
});
