import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: scale(15),
    backgroundColor: 'transparent',
  },
  instructions: {
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 15.8),
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(20),
    fontWeight: '700',
    lineHeight: msFont(isSmallPhone ? 20 : isTablet ? 24 : 20.6),
    paddingHorizontal: scale(11),
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  content: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    gap: scale(15),
    paddingHorizontal: scale(7.5),
  },
  column: {
    flex: 1,
    alignItems: 'center',
  },
  columnTitle: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '900',
    color: '#58CCF7',
    marginBottom: vs(16),
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  actionItem: {
    marginBottom: vs(12),
    borderRadius: ms(16),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    width: '100%',
  },
  obligationItem: {
    marginBottom: vs(12),
    borderRadius: ms(16),
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    width: '100%',
  },
  selectedAction: {
    transform: [{ scale: 1.03 }],
    elevation: 6,
  },
  matchedAction: {
    opacity: 0.88,
  },
  correctMatch: {
    elevation: 6,
  },
  incorrectMatch: {
    elevation: 6,
  },
  itemGradient: {
    paddingHorizontal: scale(15),
    paddingVertical: vs(18),
    borderRadius: ms(16),
    minHeight: vh(9.5),
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.4)',
  },
  itemSelected: {
    borderWidth: 3,
    borderColor: '#58CCF7',
    shadowColor: '#58CCF7',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  itemMatched: {
    borderColor: '#4a5568',
    opacity: 0.92,
  },
  itemCorrect: {
    borderWidth: 3,
    borderColor: '#10b981',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  itemIncorrect: {
    borderWidth: 3,
    borderColor: '#ef4444',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
  itemText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 14.3),
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: msFont(isSmallPhone ? 18 : isTablet ? 22 : 19.5),
  },
  completionMessage: {
    position: 'absolute',
    top: vh(30),
    left: vw(10),
    right: vw(10),
    zIndex: 1000,
  },
  completionCardNeon: {
    padding: scale(20.6),
    borderRadius: ms(18),
    alignItems: 'center',
    backgroundColor: '#000',
    borderWidth: 2,
    borderColor: '#00E5FF',
    shadowColor: '#00E5FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
  },
  completionTextNeon: {
    fontSize: msFont(isSmallPhone ? 19 : isTablet ? 24 : 21.8),
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: vs(6),
  },
  completionSubtextNeon: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 18 : 18.75),
  },
  progress: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    color: '#58CCF7',
    textAlign: 'center',
    marginTop: vs(20),
    fontWeight: '700',
    textShadowColor: 'rgba(88, 204, 247, 0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
});
