import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: scale(15),
    paddingBottom: vh(15),
  },
  title: {
    fontSize: msFont(isSmallPhone ? 22 : isTablet ? 28 : 24.4),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(31, 45, 85, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(20),
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    paddingHorizontal: scale(15),
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
    fontFamily: 'Century Gothic',
  },
  hintBox: {
    borderRadius: ms(15),
    padding: scale(15),
    marginBottom: vs(24),
    borderWidth: 1,
    borderColor: 'rgba(88, 204, 247, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  hintText: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 0.5,
    fontFamily: 'Century Gothic',
  },
  itemsContainer: {
    marginBottom: vs(24),
    gap: vs(12),
  },
  stepCard: {
    borderRadius: ms(20),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  completedCard: {
    borderColor: '#28A745',
    borderWidth: 3,
    transform: [{ scale: 1.02 }],
  },
  stepGradient: {
    padding: scale(15),
    minHeight: vh(12),
    justifyContent: 'center',
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(8),
  },
  stepIcon: {
    fontSize: msFont(isSmallPhone ? 28 : 30),
  },
  stepNumber: {
    fontSize: msFont(isSmallPhone ? 20 : isTablet ? 25 : 22.5),
    fontWeight: '900',
    color: '#FFFFFF',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: scale(15),
    width: scale(30),
    height: scale(30),
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: scale(30),
  },
  stepTitle: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 23 : 20.6),
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(6),
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  stepDescription: {
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 16 : 14.3),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 19 : isTablet ? 23 : 20.6),
    marginBottom: vs(12),
    paddingHorizontal: scale(7.5),
    fontFamily: 'Century Gothic',
  },
  moveButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(15),
  },
  moveButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: scale(22.5),
    width: scale(45),
    height: scale(45),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  moveButtonText: {
    fontSize: msFont(isSmallPhone ? 20 : 22.5),
    fontWeight: '900',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  actionButtons: {
    gap: vs(12),
    marginBottom: vs(16),
  },
  checkButton: {
    borderRadius: ms(20),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  resetButton: {
    borderRadius: ms(20),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(108, 117, 125, 0.6)',
    ...Platform.select({
      ios: {
        shadowColor: '#6C757D',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  buttonGradient: {
    paddingVertical: vs(16),
    paddingHorizontal: scale(22.5),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: ms(18),
  },
  buttonText: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 21 : 18.75),
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  attemptsText: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
});
