import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(isSmallPhone ? 16 : 19),
    paddingVertical: vs(30),
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    color: '#E0E0E0',
    textAlign: 'center',
    marginBottom: vs(30),
    lineHeight: msFont(isSmallPhone ? 19 : 20.6),
  },
  targetBox: {
    width: vw(80),
    minHeight: vh(14),
    borderRadius: ms(14),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: vs(30),
    backgroundColor: '#0B0B10',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  completedTargetBox: {
    borderColor: '#00E5FF',
    shadowColor: '#00E5FF',
  },
  targetLabel: {
    fontSize: msFont(isSmallPhone ? 12 : 13),
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: vs(8),
    marginBottom: vs(5),
  },
  targetContent: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  placeholder: {
    fontSize: msFont(isSmallPhone ? 12 : 13),
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  dragItemsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: scale(14),
    marginBottom: vs(30),
  },
  dragItem: {
    backgroundColor: '#101018',
    borderRadius: ms(10),
    paddingHorizontal: scale(15),
    paddingVertical: vs(12),
    borderWidth: 1.25,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  draggingItem: {
    opacity: 0.7,
    transform: [{ scale: 1.05 }],
  },
  dragItemText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 12 : 13),
    fontWeight: '500',
    textAlign: 'center',
  },
  continueButton: {
    backgroundColor: '#00E5FF',
    borderRadius: ms(25),
    paddingHorizontal: scale(isSmallPhone ? 24 : 28),
    paddingVertical: vs(15),
    shadowColor: '#00E5FF',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(30),
  },
  modalCard: {
    width: '100%',
    backgroundColor: '#0B0B10',
    borderRadius: ms(18),
    borderWidth: 2,
    borderColor: '#00E5FF',
    paddingTop: vs(16),
    paddingBottom: vs(16),
    paddingHorizontal: scale(19),
  },
  feedbackBadge: {
    alignSelf: 'center',
    borderRadius: ms(999),
    paddingVertical: vs(10),
    paddingHorizontal: scale(22.5),
    marginTop: vs(4),
    marginBottom: vs(10),
    borderWidth: 2,
  },
  feedbackBadgeCorrect: {
    backgroundColor: '#00E5FF',
    borderColor: 'rgba(0, 229, 255, 0.8)',
  },
  feedbackBadgeIncorrect: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255,255,255,0.5)',
  },
  feedbackBadgeTextDark: {
    color: '#0B0B10',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '800',
    textAlign: 'center',
  },
  feedbackBadgeTextLight: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '800',
    textAlign: 'center',
  },
  modalText: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    color: '#E0E0E0',
    textAlign: 'center',
    marginBottom: vs(16),
    lineHeight: msFont(isSmallPhone ? 19 : 20.6),
  },
  primaryButton: {
    backgroundColor: '#00E5FF',
    borderRadius: ms(28),
    paddingVertical: vs(14),
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#0B0B10',
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderRadius: ms(28),
    paddingVertical: vs(14),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '700',
  },
});
