import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: scale(15),
    paddingBottom: vh(15),
  },
  title: {
    fontSize: msFont(isSmallPhone ? 22 : isTablet ? 28 : 24.4),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(31, 45, 85, 1)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(20),
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    paddingHorizontal: scale(15),
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
    fontFamily: 'Century Gothic',
  },
  hintBox: {
    borderRadius: ms(15),
    padding: scale(15),
    marginBottom: vs(24),
    borderWidth: 1,
    borderColor: 'rgba(88, 204, 247, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  hintText: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 0.5,
    fontFamily: 'Century Gothic',
  },
  meterContainer: {
    borderRadius: ms(20),
    padding: scale(15),
    marginBottom: vs(24),
    borderWidth: 2,
    borderColor: 'rgba(0,229,255,0.6)',
    minHeight: vh(25),
    position: 'relative',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  electricEffects: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  sparkle: {
    position: 'absolute',
    fontSize: msFont(isSmallPhone ? 28 : 30),
    zIndex: 2,
  },
  meterTitle: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 21 : 18.75),
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: vs(16),
    textShadowColor: 'rgba(31, 45, 85, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  meterDisplay: {
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderRadius: ms(15),
    padding: scale(15),
    marginBottom: vs(16),
    borderWidth: 1,
    borderColor: 'rgba(0,229,255,0.4)',
    alignItems: 'center',
    overflow: 'hidden',
  },
  displayGradient: {
    borderRadius: ms(12),
    padding: scale(11),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: vs(8),
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  displayContainer: {
    position: 'relative',
    width: '100%',
    borderRadius: ms(12),
    overflow: 'hidden',
  },
  shimmerOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '35%',
    opacity: 0.35,
  },
  glassHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: vs(16),
    opacity: 0.35,
  },
  meterValue: {
    fontSize: msFont(isSmallPhone ? 40 : isTablet ? 52 : 45),
    fontWeight: '900',
    color: '#58CCF7',
    textShadowColor: 'rgba(0, 229, 255, 0.9)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 2,
  },
  meterValueActive: {
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 229, 255, 1)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 18,
  },
  meterLabel: {
    fontSize: msFont(isSmallPhone ? 12 : 13),
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: vs(8),
    fontFamily: 'Century Gothic',
  },
  resultCard: {
    borderRadius: ms(15),
    padding: scale(15),
    marginTop: vs(16),
    alignItems: 'center',
    borderWidth: 0,
    minWidth: scale(isSmallPhone ? 200 : 225),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  resultTitle: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#0b1a2d',
    marginBottom: vs(6),
    fontFamily: 'Century Gothic',
  },
  resultPayment: {
    fontSize: msFont(isSmallPhone ? 20 : isTablet ? 26 : 22.5),
    fontWeight: '900',
    color: '#0b1a2d',
    textShadowColor: 'rgba(255, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    fontFamily: 'Century Gothic',
  },
  resultLabel: {
    fontSize: msFont(isSmallPhone ? 12 : 13),
    fontWeight: '500',
    color: 'rgba(11, 26, 45, 0.8)',
    marginTop: vs(4),
    fontFamily: 'Century Gothic',
  },
  optionsTitle: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 21 : 18.75),
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    fontFamily: 'Century Gothic',
  },
  optionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: vs(24),
    gap: vs(12),
  },
  optionCard: {
    width: '48%',
    borderRadius: ms(15),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  selectedOption: {
    borderColor: '#FFFFFF',
    borderWidth: 2,
    transform: [{ scale: 1.02 }],
  },
  optionInner: {
    padding: scale(15),
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: vh(12),
  },
  optionKwh: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 23 : 20.6),
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: vs(4),
    fontFamily: 'Century Gothic',
  },
  optionCategory: {
    fontSize: msFont(isSmallPhone ? 11 : isTablet ? 14 : 12.8),
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: vs(6),
    fontFamily: 'Century Gothic',
  },
  optionPayment: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Century Gothic',
  },
  educationalNote: {
    borderRadius: ms(15),
    padding: scale(15),
    marginBottom: vs(24),
    borderWidth: 1,
    borderColor: 'rgba(31, 45, 85, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  noteTitle: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: vs(8),
    textShadowColor: 'rgba(31, 45, 85, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    fontFamily: 'Century Gothic',
  },
  noteText: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: msFont(isSmallPhone ? 19 : 20.6),
    textAlign: 'center',
    fontFamily: 'Century Gothic',
  },
  actionButtons: {
    gap: vs(12),
    marginBottom: vs(16),
  },
  neonButton: {
    borderRadius: ms(16),
    borderWidth: 2,
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(31,45,85,0.9)',
    paddingVertical: vs(14.5),
    alignItems: 'center',
  },
  neonButtonDisabled: {
    borderColor: 'rgba(88, 204, 247, 0.35)',
    backgroundColor: 'rgba(31,45,85,0.6)',
  },
  neonButtonText: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 20 : 18),
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: 'Century Gothic',
  },
  neonGhostButton: {
    borderRadius: ms(14),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingVertical: vs(11),
    alignItems: 'center',
  },
  neonGhostButtonText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.5),
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Century Gothic',
  },
  inlineWarning: {
    marginTop: vs(5),
    textAlign: 'center',
    color: 'rgba(255,255,255,0.85)',
    fontSize: msFont(isSmallPhone ? 13 : 15),
  },
  linkInfo: {
    borderRadius: ms(15),
    padding: scale(15),
    borderWidth: 1,
    borderColor: 'rgba(88, 204, 247, 0.3)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  linkTitle: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: vs(8),
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    fontFamily: 'Century Gothic',
  },
  linkText: {
    fontSize: msFont(isSmallPhone ? 13 : 15),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: msFont(isSmallPhone ? 19 : 20.6),
    textAlign: 'center',
    fontFamily: 'Century Gothic',
  },
});
