import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: ms(20),
    paddingTop: ms(20),
  },
  title: {
    fontSize: msFont(isSmallPhone ? 22 : isTablet ? 28 : 26),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: ms(10),
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 19 : 18),
    color: '#E8E4F3',
    textAlign: 'center',
    marginBottom: ms(20),
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  progressContainer: {
    marginBottom: ms(20),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    padding: ms(18),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  progressText: {
    fontSize: msFont(isSmallPhone ? 14 : 16),
    color: '#FFFFFF',
    fontWeight: '700',
    marginBottom: ms(12),
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  progressBar: {
    height: ms(10),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 6,
  },
  gameContainer: {
    flex: 1,
    marginBottom: ms(20),
  },
  sectionTitle: {
    fontSize: msFont(isSmallPhone ? 17 : isTablet ? 22 : 20),
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: ms(18),
    marginTop: ms(15),
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  termsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 30,
  },
  chipsContainer: {
    flexDirection: 'column',
    width: '100%',
    alignSelf: 'stretch',
    paddingHorizontal: ms(8),
    marginBottom: ms(20),
  },
  termChip: {
    width: '100%',
    minHeight: ms(48),
    paddingVertical: ms(12),
    paddingHorizontal: ms(16),
    marginBottom: ms(12),
    borderRadius: 12,
    backgroundColor: '#1e3a8a',
    borderWidth: 1.5,
    borderColor: '#3b82f6',
  },
  termChipSelected: {
    borderColor: '#94a3b8',
    borderWidth: 2,
    backgroundColor: '#475569',
  },
  termChipMatched: {
    backgroundColor: '#64748b',
    borderColor: '#94a3b8',
    transform: [{ scale: 0.98 }],
    opacity: 0.85,
  },
  chipInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  chipText: {
    color: '#ffffff',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 19 : 18),
    fontWeight: '800',
    letterSpacing: 0.2,
    textAlign: 'left',
  },
  termCard: {
    width: scale(isSmallPhone ? 140 : isTablet ? 190 : 158),
    height: ms(85),
    marginBottom: ms(14),
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: 'rgba(30, 58, 138, 0.85)',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.4)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  selectedCard: {
    transform: [{ scale: 1.05 }],
    shadowColor: '#94a3b8',
    borderColor: '#94a3b8',
    borderWidth: 2,
    backgroundColor: 'rgba(71, 85, 105, 0.9)',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 12,
  },
  matchedCard: {
    transform: [{ scale: 0.96 }],
    opacity: 0.75,
    backgroundColor: 'rgba(100, 116, 139, 0.85)',
    borderColor: '#94a3b8',
  },
  cardGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: ms(10),
    backgroundColor: 'rgba(30, 58, 138, 0.85)',
  },
  termIcon: {
    fontSize: msFont(isSmallPhone ? 24 : 28),
    marginBottom: ms(10),
  },
  termText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 19 : 18),
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 20 : isTablet ? 26 : 24),
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  checkIcon: {
    position: 'absolute',
    top: ms(10),
    right: ms(10),
    fontSize: msFont(isSmallPhone ? 20 : 24),
  },
  definitionsContainer: {
    marginBottom: ms(20),
  },
  definitionCard: {
    width: '100%',
    marginBottom: ms(12),
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: 'rgba(30, 58, 138, 0.85)',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.4)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  definitionGradient: {
    padding: ms(14),
    minHeight: ms(70),
    justifyContent: 'center',
    position: 'relative',
    backgroundColor: 'rgba(30, 58, 138, 0.85)',
  },
  definitionScroll: {
    maxHeight: vh(45),
  },
  definitionText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 19 : 18),
    color: '#FFFFFF',
    fontWeight: '700',
    lineHeight: msFont(isSmallPhone ? 20 : isTablet ? 26 : 24),
    textAlign: 'left',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  checkIconDef: {
    position: 'absolute',
    top: ms(12),
    right: ms(12),
    fontSize: msFont(isSmallPhone ? 19 : 22),
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: ms(18),
  },
  resetButton: {
    borderRadius: 30,
    overflow: 'hidden',
    shadowColor: '#3B82F6',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.7,
    shadowRadius: 12,
    elevation: 15,
  },
  continueButton: {
    borderRadius: 30,
    overflow: 'hidden',
    shadowColor: '#58CCF7',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 20,
  },
  buttonGradient: {
    paddingVertical: ms(14),
    paddingHorizontal: ms(28),
    borderRadius: 30,
  },
  buttonText: {
    fontSize: msFont(isSmallPhone ? 15 : 17),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  statsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    padding: ms(16),
    marginBottom: ms(15),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 6,
  },
  statsText: {
    fontSize: msFont(isSmallPhone ? 14 : 16),
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
