import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: scale(9.4),
    paddingVertical: vs(20),
    paddingBottom: vh(12),
  },
  title: {
    fontSize: msFont(isSmallPhone ? 17 : isTablet ? 21 : 18.75),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(10),
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 15 : 13.1),
    color: '#E0E0E0',
    textAlign: 'center',
    marginBottom: vs(15),
    paddingHorizontal: scale(19),
    lineHeight: msFont(isSmallPhone ? 15 : isTablet ? 19 : 16.9),
  },
  imageContainer: {
    position: 'relative',
    width: vw(90),
    minHeight: vh(30),
    maxHeight: vh(55),
    marginBottom: vs(15),
    alignItems: 'center',
    justifyContent: 'center',
  },
  facturaImage: {
    width: '100%',
    height: '100%',
  },
  sectionButton: {
    position: 'absolute',
    width: scale(isSmallPhone ? 24 : isTablet ? 30 : 26.3),
    height: scale(isSmallPhone ? 24 : isTablet ? 30 : 26.3),
    borderRadius: scale(isSmallPhone ? 12 : isTablet ? 15 : 13.1),
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFA500',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  viewedButton: {
    backgroundColor: '#4CAF50',
    borderColor: '#45a049',
  },
  sectionNumber: {
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 15 : 13.1),
    fontWeight: 'bold',
    color: '#000',
  },
  viewedNumber: {
    color: '#FFFFFF',
  },
  progressContainer: {
    width: vw(85),
    marginBottom: vs(15),
  },
  progressText: {
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 15 : 13.1),
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(8),
    fontWeight: '600',
  },
  progressBar: {
    height: vs(8),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: ms(4),
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#2EC5FF',
    borderRadius: ms(4),
  },
  explanationModal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    width: vw(85),
    maxHeight: vh(60),
    borderRadius: ms(18),
    paddingHorizontal: scale(19),
    paddingVertical: vs(32),
    backgroundColor: '#000',
    borderWidth: 2,
    borderColor: '#00E5FF',
    shadowColor: '#00E5FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 14,
  },
  closeButton: {
    position: 'absolute',
    top: vs(15),
    right: scale(14),
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  closeButtonText: {
    fontSize: msFont(15),
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  modalTitle: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(15),
    marginTop: vs(10),
    textShadowColor: 'rgba(0, 229, 255, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  modalScroll: {
    maxHeight: vh(38),
  },
  modalDescription: {
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 15 : 13.1),
    color: '#FFFFFF',
    lineHeight: msFont(isSmallPhone ? 17 : isTablet ? 21 : 18.75),
    textAlign: 'justify',
  },
  ctaButton: {
    position: 'absolute',
    bottom: vs(30),
    left: scale(30),
    right: scale(30),
    borderRadius: ms(14),
    borderWidth: 2,
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(31,45,85,0.85)',
    paddingVertical: vs(13),
    alignItems: 'center',
  },
  ctaText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 19 : 17.3),
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
