import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: ms(20),
    justifyContent: 'center',
  },
  title: {
    fontSize: msFont(isSmallPhone ? 20 : isTablet ? 26 : 24),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(8),
    paddingHorizontal: scale(10),
  },
  subtitle: {
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 16),
    color: '#B8B8B8',
    textAlign: 'center',
    marginBottom: vs(20),
    paddingHorizontal: scale(10),
  },
  score: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 19 : 18),
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginBottom: vs(20),
    backgroundColor: 'rgba(88, 204, 247, 0.1)',
    borderRadius: ms(15),
    paddingVertical: vs(8),
    paddingHorizontal: scale(16),
    alignSelf: 'center',
  },
  dropZonesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: vs(20),
    paddingHorizontal: scale(5),
  },
  dropZone: {
    flex: 1,
    marginHorizontal: scale(5),
    borderRadius: ms(15),
    borderWidth: 2,
    borderStyle: 'dashed',
    minHeight: vh(25),
    padding: scale(12),
  },
  yesZone: {
    borderColor: '#4CAF50',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
  },
  noZone: {
    borderColor: '#F44336',
    backgroundColor: 'rgba(244, 67, 54, 0.1)',
  },
  zoneTitle: {
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 16),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(10),
  },
  zoneContent: {
    flex: 1,
  },
  placedItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: ms(10),
    padding: scale(8),
    marginBottom: vs(6),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  placedItemText: {
    fontSize: msFont(isSmallPhone ? 11 : isTablet ? 13 : 12),
    color: '#FFFFFF',
    flex: 1,
    marginRight: scale(8),
  },
  checkMark: {
    fontSize: msFont(16),
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  emptyZoneText: {
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 15 : 14),
    color: '#888888',
    textAlign: 'center',
    marginTop: vs(20),
    fontStyle: 'italic',
  },
  statementsContainer: {
    maxHeight: vh(30),
  },
  statementsTitle: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 19 : 18),
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: vs(10),
    textAlign: 'center',
  },
  statementItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: ms(12),
    padding: scale(12),
    marginBottom: vs(8),
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedStatement: {
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(88, 204, 247, 0.2)',
    transform: [{ scale: 1.02 }],
  },
  statementText: {
    fontSize: msFont(isSmallPhone ? 13 : isTablet ? 15 : 14),
    color: '#FFFFFF',
    lineHeight: msFont(20),
  },
  selectedIndicator: {
    marginTop: vs(8),
    alignItems: 'center',
  },
  selectedIndicatorText: {
    fontSize: msFont(12),
    color: '#58CCF7',
    fontWeight: '600',
  },
  completionMessage: {
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderRadius: ms(15),
    padding: scale(16),
    marginTop: vs(20),
    alignItems: 'center',
  },
  completionText: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 22 : 20),
    fontWeight: 'bold',
    color: '#4CAF50',
    textAlign: 'center',
  },
  completionSubText: {
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 16),
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: vs(8),
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: vw(85),
    maxWidth: scale(400),
    borderRadius: ms(20),
    padding: scale(24),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  modalTitle: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 22 : 20),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(12),
  },
  modalMessage: {
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 16),
    color: '#E0E0E0',
    textAlign: 'center',
    lineHeight: msFont(22),
    marginBottom: vs(24),
  },
  modalButton: {
    borderRadius: ms(25),
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalButtonGradient: {
    paddingVertical: vs(12),
    paddingHorizontal: scale(32),
    alignItems: 'center',
    minWidth: scale(120),
  },
  modalButtonText: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 19 : 18),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
