// src/screens/Home/styles.ts
import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#1F2D55',
    paddingTop: vs(40),
    paddingHorizontal: scale(20),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(20),
    paddingHorizontal: ms(5),
    paddingVertical: vs(10),
  },
  greeting: {
    fontSize: msFont(isSmallPhone ? 16 : 18),
    color: '#fff',
    fontFamily: 'Century Gothic',
    lineHeight: msFont(isSmallPhone ? 22 : 24),
  },
  username: {
    fontWeight: 'bold',
    color: '#FFC107',
    fontFamily: 'Century Gothic',
  },
  wave: {
    fontSize: msFont(20),
  },
  logo: {
    width: scale(isTablet ? 120 : 90),
    height: vs(40),
    resizeMode: 'contain',
  },
  scrollContent: {
    paddingBottom: vs(120),
  },
  cardPrimary: {
    borderRadius: ms(20),
    padding: ms(isSmallPhone ? 14 : 18),
    marginBottom: vs(16),
    minHeight: vs(isSmallPhone ? 150 : isTablet ? 190 : 170),
    borderBottomWidth: ms(6),
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
  },
  cardSecondary: {
    borderRadius: ms(20),
    padding: ms(isSmallPhone ? 14 : 18),
    marginBottom: vs(16),
    minHeight: vs(isSmallPhone ? 150 : isTablet ? 190 : 170),
    borderBottomWidth: ms(6),
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
  },
  cardTertiary: {
    borderRadius: ms(20),
    padding: ms(isSmallPhone ? 14 : 18),
    marginBottom: vs(16),
    minHeight: vs(isSmallPhone ? 150 : isTablet ? 190 : 170),
    borderBottomWidth: ms(6),
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
  },
  cardQuaternary: {
    borderRadius: ms(20),
    padding: ms(isSmallPhone ? 14 : 18),
    marginBottom: vs(16),
    minHeight: vs(isSmallPhone ? 150 : isTablet ? 190 : 170),
    borderBottomWidth: ms(6),
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
  },
  cardQuinary: {
    borderRadius: ms(20),
    padding: ms(isSmallPhone ? 14 : 18),
    marginBottom: vs(16),
    minHeight: vs(isSmallPhone ? 150 : isTablet ? 190 : 170),
    borderBottomWidth: ms(6),
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
  },
  cardSenary: {
    borderRadius: ms(20),
    padding: ms(isSmallPhone ? 14 : 18),
    marginBottom: vs(16),
    minHeight: vs(isSmallPhone ? 150 : isTablet ? 190 : 170),
    borderBottomWidth: ms(6),
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 12,
  },
  cardLabel: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: msFont(isSmallPhone ? 13 : 15),
    marginBottom: ms(4),
  },
  cardTitle: {
    color: '#fff',
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 19 : 17),
    fontWeight: 'bold',
    marginBottom: ms(4),
    lineHeight: msFont(isSmallPhone ? 20 : isTablet ? 26 : 22),
  },
  cardSubtitle: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: msFont(isSmallPhone ? 12 : 13),
    marginBottom: ms(8),
    fontStyle: 'italic',
  },
  cardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(6),
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: ms(14),
    paddingHorizontal: ms(10),
    paddingVertical: ms(4),
    marginRight: ms(8),
    marginTop: ms(4),
  },
  infoIcon: {
    marginRight: ms(6),
  },
  cardInfo: {
    color: '#fff',
    fontSize: msFont(isSmallPhone ? 11 : 12),
    flexShrink: 1,
  },
  cardContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardImageRight: {
    width: scale(isSmallPhone ? 90 : isTablet ? 130 : 110),
    height: scale(isSmallPhone ? 90 : isTablet ? 130 : 110),
    resizeMode: 'contain',
    marginLeft: ms(10),
  },
  cardImageLeft: {
    width: scale(isSmallPhone ? 70 : isTablet ? 100 : 80),
    height: scale(isSmallPhone ? 70 : isTablet ? 100 : 80),
    resizeMode: 'contain',
    marginRight: ms(10),
  },
  cardImage: {
    width: '100%',
    height: vs(isSmallPhone ? 100 : isTablet ? 140 : 120),
    resizeMode: 'contain',
    marginBottom: ms(10),
  },
  tabGroup: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: ms(8),
    marginVertical: vs(16),
    flexWrap: 'wrap',
  },
  tab: {
    backgroundColor: '#fff',
    borderRadius: ms(20),
    paddingHorizontal: ms(16),
    paddingVertical: vs(10),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: {
    color: '#333',
    fontWeight: 'bold',
    fontSize: msFont(13),
  },
  tabActive: {
    backgroundColor: '#8B5CF6',
    borderRadius: ms(20),
    paddingHorizontal: ms(16),
    paddingVertical: vs(10),
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
  },
  tabActiveText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: msFont(13),
  },
  bottomMenu: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingVertical: vs(14),
    paddingBottom: vs(24),
    borderTopLeftRadius: ms(20),
    borderTopRightRadius: ms(20),
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 6,
  },
  menuButton: {
    alignItems: 'center',
  },
  menuText: {
    color: '#1F2D55',
    fontSize: msFont(11),
    marginTop: ms(4),
    fontFamily: 'Century Gothic',
  },
  menuButtonActive: {
    alignItems: 'center',
  },
  menuTextActive: {
    color: '#FF7A00',
    fontSize: msFont(11),
    fontWeight: 'bold',
    marginTop: ms(4),
  },
});
