import { StyleSheet } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: scale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: msFont(isSmallPhone ? 20 : isTablet ? 26 : 24),
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: vs(10),
    textAlign: 'center',
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 14 : isTablet ? 17 : 16),
    color: '#E8E4F3',
    textAlign: 'center',
    marginBottom: vs(20),
    paddingHorizontal: scale(10),
  },
  meterContainer: {
    width: vw(85),
    height: vh(15),
    borderRadius: ms(15),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: vs(20),
    borderWidth: 3,
    borderColor: '#34495E',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  meterLabel: {
    fontSize: msFont(isSmallPhone ? 11 : isTablet ? 13 : 11.3),
    fontWeight: '600',
    color: '#BDC3C7',
    marginBottom: vs(5),
  },
  meterDigitsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(7.5),
  },
  meterDigitContainer: {
    width: scale(isSmallPhone ? 35 : isTablet ? 45 : 37.5),
    height: vs(50),
    backgroundColor: '#1C2833',
    borderRadius: ms(8),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#34495E',
  },
  meterDigit: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  meterDigitText: {
    fontSize: msFont(isSmallPhone ? 20 : isTablet ? 26 : 22.5),
    fontWeight: 'bold',
    color: '#00FF41',
    fontFamily: 'monospace',
  },
  inputLabel: {
    fontSize: msFont(15),
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: vs(10),
  },
  inputRow: {
    flexDirection: 'row',
    gap: scale(9.4),
    marginBottom: vs(20),
  },
  inputBox: {
    width: scale(isSmallPhone ? 35 : isTablet ? 45 : 37.5),
    height: vs(50),
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: ms(8),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  selectedInputBox: {
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(88, 204, 247, 0.2)',
  },
  inputText: {
    fontSize: msFont(isSmallPhone ? 17 : isTablet ? 21 : 18.75),
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  numberPad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: scale(9.4),
    marginBottom: vs(20),
    maxWidth: vw(80),
  },
  numberButton: {
    width: scale(isSmallPhone ? 45 : isTablet ? 60 : 47),
    height: scale(isSmallPhone ? 45 : isTablet ? 60 : 47),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: scale(isSmallPhone ? 22.5 : isTablet ? 30 : 23.5),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  numberButtonText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: scale(14),
    marginBottom: vs(20),
  },
  resetButton: {
    backgroundColor: '#E74C3C',
    borderRadius: ms(20),
    paddingHorizontal: scale(19),
    paddingVertical: vs(10),
    shadowColor: '#E74C3C',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  resetButtonText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 14 : 13.1),
    fontWeight: '600',
  },
  checkButton: {
    backgroundColor: 'rgba(52, 152, 219, 0.6)',
    borderRadius: ms(20),
    paddingHorizontal: scale(19),
    paddingVertical: vs(10),
    shadowColor: '#3498DB',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  checkButtonActive: {
    backgroundColor: '#3498DB',
  },
  checkButtonText: {
    color: '#FFFFFF',
    fontSize: msFont(isSmallPhone ? 12 : isTablet ? 14 : 13.1),
    fontWeight: '600',
  },
  continueButton: {
    backgroundColor: '#27AE60',
    borderRadius: ms(25),
    paddingHorizontal: scale(28),
    paddingVertical: vs(15),
    shadowColor: '#27AE60',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: msFont(15),
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
