import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: scale(15),
    paddingBottom: vh(15),
  },
  title: {
    fontSize: msFont(isSmallPhone ? 22 : isTablet ? 28 : 24.4),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(0, 229, 255, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  instruction: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(20),
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    paddingHorizontal: scale(15),
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
  progressContainer: {
    alignItems: 'center',
    marginBottom: vs(24),
    paddingVertical: vs(16),
  },
  progressText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: vs(12),
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  progressBar: {
    width: vw(80),
    height: vs(10),
    backgroundColor: 'rgba(26, 0, 51, 0.8)',
    borderRadius: ms(15),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.5)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  progressFill: {
    height: '100%',
    borderRadius: ms(15),
  },
  invoiceContainer: {
    borderRadius: ms(20),
    padding: scale(15),
    marginBottom: vs(24),
    borderWidth: 3,
    borderColor: '#8B45FF',
    minHeight: vh(35),
    position: 'relative',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  invoiceTitle: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 21 : 18.75),
    fontWeight: '900',
    color: '#1a0033',
    textAlign: 'center',
    marginBottom: vs(16),
    letterSpacing: 1,
  },
  clickableSection: {
    position: 'absolute',
    borderRadius: ms(8),
    borderWidth: 2,
    borderColor: 'rgba(139, 69, 255, 0.6)',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#8B45FF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  exploredSection: {
    borderColor: '#28A745',
    borderWidth: 3,
    transform: [{ scale: 1.02 }],
  },
  sectionGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(7.5),
    borderRadius: ms(6),
  },
  sectionLabel: {
    fontSize: msFont(isSmallPhone ? 11 : isTablet ? 13 : 12),
    fontWeight: '700',
    color: '#1a0033',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 14 : 15),
  },
  completeButton: {
    alignSelf: 'center',
    borderRadius: ms(16),
    borderWidth: 2,
    borderColor: '#58CCF7',
    backgroundColor: 'rgba(31,45,85,0.85)',
    paddingVertical: vs(13),
    paddingHorizontal: scale(45),
    marginTop: vs(16),
  },
  completeButtonText: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 20 : 18),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  explanationOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: scale(19),
    paddingBottom: vh(5),
  },
  explanationCard: {
    width: vw(90),
    maxHeight: vh(55),
    borderRadius: ms(18),
    padding: scale(22.5),
    alignItems: 'center',
    backgroundColor: '#000',
    borderWidth: 0,
    ...Platform.select({
      ios: {
        shadowColor: '#00E5FF',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.6,
        shadowRadius: 16,
      },
      android: {
        elevation: 18,
      },
    }),
  },
  neonLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#00E5FF',
    ...Platform.select({
      ios: {
        shadowColor: '#00E5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.9,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  explanationTitle: {
    fontSize: msFont(isSmallPhone ? 20 : isTablet ? 26 : 22.5),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(0, 229, 255, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  explanationScroll: {
    maxHeight: vh(35),
    alignSelf: 'stretch',
  },
  explanationText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    marginBottom: vs(24),
    paddingHorizontal: scale(7.5),
  },
  closeButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: ms(14),
    paddingVertical: vs(11),
    paddingHorizontal: scale(22.5),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  closeButtonText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 17),
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 229, 255, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
    letterSpacing: 0.5,
  },
});
