import { StyleSheet, Platform } from 'react-native';
import { moderateScale as ms, msFont, verticalScale as vs, scale, deviceInfo, vw, vh } from '../../utils/responsive';

const { isTablet, isSmallPhone } = deviceInfo();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: scale(19),
    paddingBottom: vh(15),
  },
  progressContainer: {
    alignItems: 'center',
    marginBottom: vs(32),
    paddingVertical: vs(16),
  },
  progressText: {
    fontSize: msFont(isSmallPhone ? 17 : isTablet ? 21 : 18.75),
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: vs(20),
    textAlign: 'center',
    textShadowColor: 'rgba(88, 204, 247, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  progressBar: {
    width: vw(85),
    height: vs(12),
    backgroundColor: 'rgba(31, 45, 85, 0.8)',
    borderRadius: ms(20),
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(88, 204, 247, 0.5)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  progressFill: {
    height: '100%',
    borderRadius: ms(20),
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  questionCard: {
    marginVertical: vs(24),
    borderRadius: ms(20),
    padding: scale(22.5),
    borderWidth: 3,
    borderColor: 'rgba(31, 45, 85, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: vh(15),
    ...Platform.select({
      ios: {
        shadowColor: '#1f2d55',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  questionText: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 23 : 20.6),
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 24 : isTablet ? 30 : 26.3),
    letterSpacing: 0.5,
    textShadowColor: 'rgba(31, 45, 85, 1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    fontFamily: 'Century Gothic',
  },
  answersContainer: {
    marginVertical: vs(24),
    gap: vs(16),
  },
  answerButton: {
    borderRadius: ms(18),
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: 'rgba(88, 204, 247, 0.5)',
    ...Platform.select({
      ios: {
        shadowColor: '#58CCF7',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  selectedButton: {
    borderColor: '#FFFFFF',
    borderWidth: 3,
    transform: [{ scale: 1.03 }],
    ...Platform.select({
      ios: {
        shadowColor: '#FFFFFF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  answerButtonGradient: {
    paddingVertical: vs(20),
    paddingHorizontal: scale(22.5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerButtonText: {
    fontSize: msFont(isSmallPhone ? 17 : isTablet ? 21 : 18.75),
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 1,
    fontFamily: 'Century Gothic',
  },
  scoreText: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: '600',
    color: '#58CCF7',
    textAlign: 'center',
    marginTop: vs(16),
    textShadowColor: 'rgba(88, 204, 247, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
    fontFamily: 'Century Gothic',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: scale(19),
  },
  feedbackModal: {
    width: vw(90),
    borderRadius: ms(25),
    padding: scale(30),
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.8,
        shadowRadius: 25,
      },
      android: {
        elevation: 20,
      },
    }),
  },
  nextButton: {
    marginTop: vs(24),
    borderRadius: ms(20),
    overflow: 'hidden',
    width: '100%',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  nextButtonGradient: {
    paddingVertical: vs(20),
    paddingHorizontal: scale(30),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    borderRadius: ms(20),
  },
  nextButtonText: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 23 : 20.6),
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
  feedbackBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(19),
  },
  feedbackContainer: {
    width: vw(90),
    maxWidth: scale(500),
    alignItems: 'center',
  },
  feedbackStarsImage: {
    width: scale(isSmallPhone ? 140 : isTablet ? 200 : 170),
    height: vh(isSmallPhone ? 12 : isTablet ? 16 : 15),
    marginBottom: vs(20),
  },
  feedbackCard: {
    width: '100%',
    padding: scale(30),
    borderRadius: ms(24),
    marginBottom: vs(20),
    borderWidth: 3,
    borderColor: '#06b6d4',
    ...Platform.select({
      ios: {
        shadowColor: '#06b6d4',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
      },
      android: {
        elevation: 15,
      },
    }),
  },
  feedbackTitle: {
    fontSize: msFont(isSmallPhone ? 26 : isTablet ? 34 : 30),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(16),
    textShadowColor: 'rgba(6, 182, 212, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
  feedbackMessage: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
  feedbackButton: {
    width: '100%',
    borderRadius: ms(20),
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#06b6d4',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  feedbackButtonGradient: {
    paddingVertical: vs(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#0ea5e9',
    borderRadius: ms(20),
  },
  feedbackButtonText: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 23 : 20.6),
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  // Estilos para respuesta CORRECTA con imagen
  correctImageContainer: {
    width: vw(90),
    maxWidth: scale(500),
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctBackgroundImage: {
    width: vw(85),
    height: vh(60),
  },
  correctTextContainer: {
    position: 'absolute',
    top: vh(25),
    left: vw(10),
    right: vw(10),
    paddingHorizontal: scale(30),
  },
  correctMessage: {
    fontSize: msFont(isSmallPhone ? 15 : isTablet ? 18 : 16.9),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 22 : isTablet ? 27 : 24.4),
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
  correctButton: {
    position: 'absolute',
    bottom: vh(12),
    width: vw(70),
    borderRadius: ms(20),
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#06b6d4',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  correctButtonGradient: {
    paddingVertical: vs(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#0ea5e9',
    borderRadius: ms(20),
  },
  correctButtonText: {
    fontSize: msFont(isSmallPhone ? 18 : isTablet ? 23 : 20.6),
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  // Completion overlay
  completionOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  completionStarsImage: {
    width: scale(isSmallPhone ? 170 : isTablet ? 250 : 200),
    height: vh(isSmallPhone ? 18 : isTablet ? 22 : 20),
    marginBottom: vs(30),
  },
  completionCard: {
    width: '100%',
    height: '100%',
    padding: scale(37.5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  completionTitle: {
    fontSize: msFont(isSmallPhone ? 30 : isTablet ? 38 : 33.8),
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(24),
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
    letterSpacing: 1.5,
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
  completionScore: {
    fontSize: msFont(isSmallPhone ? 24 : isTablet ? 30 : 26.3),
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: vs(20),
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
  completionMessage: {
    fontSize: msFont(isSmallPhone ? 16 : isTablet ? 20 : 18),
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: msFont(isSmallPhone ? 24 : isTablet ? 30 : 26.3),
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
    fontFamily: Platform.OS === 'ios' ? 'Century Gothic' : 'sans-serif',
  },
});
